### ISSUE TITLE
server_side_encryption: 'aws:kms'

### ISSUE THREAD

**Issue by tlrdstd** [logstash-plugins/logstash-output-s3#104]
#62 added support for a boolean `server_side_encryption` flag. If it is `true`, the S3 write uses `:aes256` encryption: https://github.com/logstash-plugins/logstash-output-s3/blob/master/lib/logstash/outputs/s3.rb#L181

My application requires S3 writes to be encrypted via `'aws:kms'` instead of `:aes256`. Could the `server_side_encryption` option please be updated to accept both of these arguments supported by the AWS SDK Object API? (http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#server_side_encryption-instance_method.)

**Comment by ph** [comment]
fixed in #119

**Comment by vktor18** [comment]
hi, if `server_side_encryption` is true, will be used aes256 but what about the key? I didn't see any specific field where to put the key... Am I missing something? thanks
