### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by a86c6f7964** [logstash-plugins/logstash-output-s3#109]
I am pretty sure that this line https://github.com/logstash-plugins/logstash-output-s3/blob/dbc474bd54b64ea985ea59f70777d6d13c5be211/lib/logstash/outputs/s3.rb#L293 is supposed to be `canned_acl`

**Comment by ph** [comment]
Fixed in https://github.com/logstash-plugins/logstash-output-s3/pull/113
