### ISSUE TITLE
tag, move or remove slow test from spec suite

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-s3#11]
Currently [this test](https://github.com/logstash-plugins/logstash-output-s3/blob/master/spec/outputs/s3_spec.rb#L251-L254) can take up to a minute to complete because, in "worst case", it will write 15k events 200byte file.
Should be revisited and either:
a) moved to a stress test file
b) tagged as :slow or other excluded tag by default
c) reduced to a simpler scenario

**Comment by ph** [comment]
Current tests run under <1 minute on my machine.

**Comment by ph** [comment]
they are pretty snappy now :)
