### ISSUE TITLE
How does logstash-output-s3 handle SIGTERM?

### ISSUE THREAD

**Issue by rclmenezes** [logstash-plugins/logstash-output-s3#114]
Hi,

When I run logstash in Amazon ECS, [it gets gracefully shutdown](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_StopTask.html):

- A SIGTERM is sent
- The ECS agent waits 30s to see if there's a graceful shutdown
- A SIGKILL is sent
- The container is terminated

My containers seem to use the entire 30s. According the [Logstash docs on fault tolerance](https://www.elastic.co/guide/en/logstash/5.0/fault-tolerance.html):

> When the pipeline cannot be flushed due to a stuck output or filter, Logstash waits indefinitely. For example, when a pipeline sends output to a database that is unreachable by the Logstash instance, the instance waits indefinitely after receiving a SIGTERM.

So I have a few questions:

- Does logstash-output-s3 attempt to flush to S3 in event of a SIGTERM?

- If it does and fails to flush, will it log the error?

I don't see any errors logged in stdout, so I can't tell if logstash-output-s3 is stuck :(

Thanks!

**Comment by rclmenezes** [comment]
Fixed in a newer version of the plugin, apparently.

**Comment by ph** [comment]
@rclmenezes Just to recap what will happen is the following.

- logstash will top the input -> filter -> output
- on close the output will upload the current temporary files.
- logstash shutdown.

**Comment by jcsorvasi** [comment]
@ph Just want to confirm: logstash will shut down the input so no new message reaches the pipeline, but inflight messages will be processed, right? I mean all messages that are in memory will go through all filters and outputs and the s3 output will make sure to wait for all file uploads to finish successfully as well before shutting down cleanly.

**Comment by ph** [comment]
>  Just want to confirm: logstash will shut down the input so no new message reaches the pipeline, but inflight messages will be processed, right?

Correct,

> I mean all messages that are in memory will go through all filters and outputs and the s3 output will make sure to wait for all file uploads to finish successfully as well before shutting down cleanly.

Exactly, the queues and the local files will be send to the remote server.

**Comment by jcsorvasi** [comment]
Excellent, thank you!
