### ISSUE TITLE
Documentation Mismatch

### ISSUE THREAD

**Issue by kylegoch** [logstash-plugins/logstash-output-s3#125]
I noticed that the [documentation on Elastic's side](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-s3.html#plugins-outputs-s3-prefix) does not match the documentation found in the [plugin itself](https://github.com/logstash-plugins/logstash-output-s3/blob/master/lib/logstash/outputs/s3.rb).

Is that a manual process to update the documetation over there, or is an automated process that might not have run?

I thought the amount of options was low when i read Elastic's documentation, and wondered over here looking for gzip encoding. And sure enough there was a ton of info in the plugin.

**Comment by rclmenezes** [comment]
+1.

For example, the docs didn't include information about gzip encoding.

**Comment by kylegoch** [comment]
I have edited Elastic's documentation before. It's just a simple PR type deal, but I didnt want to go through manually doing it if there was already an automated process in place by chance.

**Comment by suyograo** [comment]
We are fixing this now. The docs build are auto-generated from the code, but they haven't been sync'd (our doc generation process was broken).

**Comment by kylegoch** [comment]
Awesome, thanks @suyograo. Thats what i wanted to confirm. It appeared to be auto-generated but I would have had no problem helping update the docs if it was manual.

Thanks for letting us know!!

(I'll leave this open till that gets sorted so there arent duplicate issues, just in case).

**Comment by suyograo** [comment]
@kylegoch just to confirm, what version of LS docs where you looking at?

**Comment by kylegoch** [comment]
@suyograo 
5.1 (current):
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-s3.html

**Comment by kylegoch** [comment]
This appears to be fixed now
