### ISSUE TITLE
restore_from_crash logic path does not use defined upload_options

### ISSUE THREAD

**Issue by kbrackney** [logstash-plugins/logstash-output-s3#140]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: logstash-5.3.1-1.noarch
- Operating System: CentOS Linux release 7.3.1611 (Core)
- Config File (if you have sensitive info, please remove it):
```
output {

   s3 {
     id => "syslog"
     region => "*****"
     bucket => "********"
     prefix => "syslog/%{+'year='yyyy}/%{+'month='M}/%{+'day='d}/%{+'hour='H}/"
     size_file => 134217728
     time_file => 60
     encoding => "gzip"
     restore => true
     canned_acl => "private"
     temporary_directory => "/var/tmp/logstash"
     server_side_encryption => true
   }
}
```

- Steps to Reproduce:

An S3 bucket has been create with a policy to deny uploads in which server side encryption is not used.    
```
{
    "Version": "2012-10-17",
    "Id": "LoggingBucketPolicy20170421",
    "Statement": [
        {
            "Sid": "DenyIncorrectEncryptionHeaderLogsData",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::**********/syslog/*",
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-server-side-encryption": "AES256"
                }
            }
        },
        {
            "Sid": "DenyUnEncryptedObjectUploadsLogsData",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::**********/syslog/*",
            "Condition": {
                "Null": {
                    "s3:x-amz-server-side-encryption": "true"
                }
            }
        }
    ]
}
```

Under normal operation, the upload of the is successfully written to the intended location.   However, under a _crash recover_ scenario, the upload fails due to the defined bucket policy:

```[2017-04-26T11:08:21,039][ERROR][logstash.outputs.s3      ] Uploading failed, retrying {:exception=>Aws::S3::Errors::AccessDenied, :message=>"Access Denied", :path=>"/var/tmp/logstash/665f7a50-0191-43e7-ac33-2212a861011c/syslog/year=2017/month=4/day=26/hour=10/ls.s3.5143f0c2-be94-46c6-823d-8be8c4bf7149.2017-04-26T11.01.part1.txt.gz", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/plugins/response_target.rb:21:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/request.rb:70:in `send_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/base.rb:207:in `put_object'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `put_object'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/object.rb:251:in `upload_file'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.6/lib/logstash/outputs/s3/uploader.rb:38:in `upload'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.6/lib/logstash/outputs/s3/uploader.rb:29:in `upload_async'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-1.0.0-java/lib/concurrent/executor/java_executor_service.rb:94:in `run'", "Concurrent$$JavaExecutorService$$Job_754842731.gen:13:in `run'"]}```

The _upload_async_ call for the _@crash_uploader_ object fails to include the same _upload_options_ hash as the normal _@uploader_

Crash Recovery
```
 @crash_uploader.upload_async(temp_file, :on_complete => method(:clean_temporary_file))
```

Normal Upload
``` 
@uploader.upload_async(temp_file, :on_complete => method(:clean_temporary_file), :upload_options => upload_options )
```

The same upload options on crash recovery are required to ensure files are uploaded with the desired specified ACLs and Encryption settings.

**Comment by ph** [comment]
Oh! good catch this is a simple fix!

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-output-s3/pull/141
