### ISSUE TITLE
IllegalLocationConstraintException

### ISSUE THREAD

**Issue by danhiris** [logstash-plugins/logstash-output-s3#142]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: 4.0.7
- Operating System:Amazon Linux AMI release 2016.09
- Config File (if you have sensitive info, please remove it): 
input {
   file {
    path => "/app/data/logs/httpd/access.log"
    type => "apache_access"
   }
   file {
    path => "/app/data/logs/httpd/error.log"
    type => "apache_error"
   }
}

output {
   s3{
     bucket => "aws.usf.mgmt.logs.app"
     region => "us-west-2"
   }
}

- Sample Data:

Just basic apache logs

- Steps to Reproduce:

start service, the following stuff goes into logstash logs over and over again. Process has to be kill -9ed 

{:timestamp=>"2017-05-11T09:39:04.898000-0500", :message=>"The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.", :exception=>Aws::S3::Errors::IllegalLocationConstraintException, :path=>"/var/lib/logstash/logstash/ls.s3.<server edited>.2017-05-11T08.56.tag_<tags edited>.part0.txt", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/plugins/response_target.rb:21:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/request.rb:70:in `send_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/base.rb:207:in `put_object'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `put_object'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/object.rb:251:in `upload_file'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.7/lib/logstash/outputs/s3/uploader.rb:38:in `upload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.7/lib/logstash/outputs/s3/uploader.rb:29:in `upload_async'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.2-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_754842468.gen:13:in `run'"], :level=>:error}

**Comment by kares** [comment]
a problem with S3 itself (related to endpoint redirection), not much LS can do about. 
for reference look at what the [aws library proposes as a work-around](https://github.com/aws/aws-cli/issues/3567)
