### ISSUE TITLE
Dynamic field values in prefix is not supported

### ISSUE THREAD

**Issue by nigoel** [logstash-plugins/logstash-output-s3#16]
Creation of different file paths in s3 for different kind of events or tracking log file is not supported. 

For example, here folder prefixes based on fields "app" and "type" are not supported.
input {
  file {
    path => "/*/data/*/executors/*/logs/*"
  }
}

filter {
  grok { match => ["path","/%{GREEDYDATA}/executors/%{GREEDYDATA:app}[.]%{GREEDYDATA}/logs/%{GREEDYDATA:type}"]
       }
  }
output {
 s3{
    .....................
    .....................
     prefix => "applogs/%{app}/%{type}"
    }
}

**Comment by nigoel** [comment]
Fix has been provided in https://github.com/nigoel/logstash-output-s3

**Comment by Onalu** [comment]
I'd like to see dynamic values on prefix too. I want to collect my logs in daily folders and there is no option for it now.

@nigoel maybe you should make a pull request since you already implemented a solution.

**Comment by nigoel** [comment]
@Onalu  Here it is https://github.com/logstash-plugins/logstash-output-s3/pull/17

**Comment by shaharmor** [comment]
+1

**Comment by vaijab** [comment]
Any plans on implementing this?

**Comment by BDuelz** [comment]
+1

**Comment by obazoud** [comment]
+1

**Comment by zot420** [comment]
+1

**Comment by NoumanSaleem** [comment]
Would love this for all other string values like `bucket`

**Comment by cero-t** [comment]
+1

**Comment by beeva-luisgonzalez** [comment]
Please merge it!

**Comment by kevart** [comment]
Please merge it!

**Comment by kevart** [comment]
@nigoel would you pull the latest version and merge your changes? So your repo is up-to-date. That would be awesome!! I've tried, but got conflicts I couldn't solve.

**Comment by kevart** [comment]
@nigoel I am using your version of the plugin as I needed dynamic prefixes. Workers stop after they've uploaded once. It seems _need_cleanup?_ throws an error if _@empty_downloads[prefix]_ is nil.
I couldn't create a pull request for [your repository](https://github.com/nigoel/logstash-output-s3) hence posting it here. The fix should look like this (or similar, I am not a ruby programmer):

```
  public
  def need_cleanup?(prefix)
    if @empty_uploads[prefix].nil?
      return false
    end
    return @empty_uploads[prefix] > @no_event_wait
  end
```

**Comment by asemt** [comment]
+1

**Comment by s4nch3z** [comment]
+1

**Comment by dgeebs** [comment]
+1

**Comment by donovankim** [comment]
+1

**Comment by wagner** [comment]
+1

**Comment by vaijab** [comment]
Adding +1 does not do anything, just spams us all.

**Comment by ph** [comment]
I am closing this issue in favor of #4, so all the discussion can happen in the same place.
I have started on working on that feature.
