### ISSUE TITLE
Option for different S3 location

### ISSUE THREAD

**Issue by kr0gh** [logstash-plugins/logstash-output-s3#170]
Hi,

Can you make it possible to specify a different endpoint, so that it can be used with other S3 endpoints?

Best regards,

Anders

**Comment by captnbp** [comment]
+1 for this request ! We are currently blocked by this to use our on premise S3 storage solution :-/

**Comment by martinohansen** [comment]
+1 from us to, we would also like to use our own object storage.

**Comment by webmat** [comment]
This is available as of v4.1.0 of the plugin (current version 4.1.1).

This has been tested with [the AWS S3 endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region), but not with other "compatible" endpoints. YMMV with those.
