### ISSUE TITLE
Upload temp files to s3 in tear down

### ISSUE THREAD

**Issue by cnhappier** [logstash-plugins/logstash-output-s3#19]
In AWS environment, there's a way to make zero-download time upgrade, using the AWS auto scaling feature. 
Details in here.
http://serverfault.com/questions/389301/amazon-ec2-elastic-load-balancing-strategy-for-zero-downtime-server-restart/679502#679502

So it's usual to close one EC2 instance and wait for the new one come to serve in the upgrade procedure.
In this situation, it's useful to upload the temp files to s3 when the s3 plugin is shutting down to avoid some log data missing after EC2 stop and terminate.

So it's nice to have a flag to enable this kind of "graceful shutdown" for this plugin.

**Comment by cnhappier** [comment]
Pull request provided: https://github.com/logstash-plugins/logstash-output-s3/pull/14

**Comment by barqshasbite** [comment]
I don't think this issue (and #68, and any other dupes) are valid anymore? The code was significantly refactored after this issue was reported and now the `close` method has this comment:

```
# The plugin has stopped receiving new events, but we still have
# data on disk, lets make sure it get to S3.
```
These issues and the related PRs can probably be closed.

**Comment by kares** [comment]
as noted above, believe this is no longer valid with the [current code in place](https://github.com/logstash-plugins/logstash-output-s3/blob/v4.3.5/lib/logstash/outputs/s3.rb#L269-L273=) (on plugin `close`)
