### ISSUE TITLE
Wrong host name and bucket when specifying endpoint

### ISSUE THREAD

**Issue by bitva77** [logstash-plugins/logstash-output-s3#199]
Running Logstash 6.3.1 (and also confirmed with 6.3.2) via Docker.

When specifying a custom endpoint, the S3 output plugin tries to connect to the server using the constructed URL of http://$bucket.$endpoint and then ignores the bucket name and tries to upload to the root (/).

For example, using the following output configuration:

```
 s3 {
 			secret_access_key => "Rj/ArKR3J6latZE3NO1o6NZDUPE0g55+strzJ2Ep"
 			access_key_id => "HPQPGF5BIGV3NNHJIJHM"
 			endpoint => "http://minioserver"
 			bucket => "click-data"
}
```

The plugin will try to connect to http://click-data.minioserver:80 and upload to /

Maybe I've misunderstood endpoint and bucket but I would think it should try to upload to http://minioserver/click-data/

Thanks!

**Comment by bitva77** [comment]
I've confirmed that uploads succeed to the root.  Or,  if we use a date as a prefix, the date prefix becomes the bucket and uploads succeed.  Not really what we want but at least we're not losing data now.

**Comment by robbavey** [comment]
@bitva77 Try adding

``` additional_settings => { force_path_style => true }```

to your configuration. That will put the bucket name in the URI, rather than moving it to the host as a subdomain. 

We use the Amazon AWS ruby API under the covers, and we inherit the behaviour of endpoints from there (see https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html)

**Comment by bonndan** [comment]
This worked for me.

**Comment by robbavey** [comment]
Closing this issue, as it appears to be solved
