### ISSUE TITLE
using lambda events

### ISSUE THREAD

**Issue by jschoch** [logstash-plugins/logstash-output-s3#25]
Any plans to use lambda events to ingest?

Seems like a simpler model, vs scanning at an interval.

**Comment by ph** [comment]
I think this will be the next things to do when I touch the plugin again, I think a community fork exist to use lambda events.

**Comment by ph** [comment]
This is mostly for the S3 input, SQS Event notification seems an easier model.

**Comment by ph** [comment]
See discussion at https://github.com/logstash-plugins/logstash-input-s3/issues/14
