### ISSUE TITLE
Gzip support

### ISSUE THREAD

**Issue by shaharmor** [logstash-plugins/logstash-output-s3#26]
Hey, any chance to add gzip support before uploading?

**Comment by lremurphy** [comment]
That would be awesome if that could be incorporated!

**Comment by ph** [comment]
Set `encoding` to 'gzip' and it will generate gzip files.

**Comment by lremurphy** [comment]
you say to specify "encoding" to "gzip", tried, that is not listed as a valid configuration option for the s3 output plugin I am using.  please advise on which version or release of the logstash-s3-output has this capability.

**Comment by ph** [comment]
@lremurphy 

The feature is coming from https://github.com/logstash-plugins/logstash-output-s3/pull/18
I would say logstash-output-s3 >= 2.0.2, and this version of the plugin should be shipping since logstash 2.0. IIRC>

**Comment by ph** [comment]
@lremurphy Which version of Logstash are you using?

**Comment by aramirez-es** [comment]
Hi, I was facing the same issue using the latest version of Logstash Docker image (currently 2.4), but finally I realized the problem was in the plugin version.

I've forced the version `$ bin/logstash-plugin install --version 3.2.0 logstash-output-s3` and that solved the issue for me.

I hope it helps.

**Comment by lremurphy** [comment]
I was using version 2.4 of logstash which is the current version listed on the elastic website documentation.  Ultimately I had to copy this file into the correct directory to get gzip compression working with the current release of logstash.
