### ISSUE TITLE
Support file compression before uploading to s3

### ISSUE THREAD

**Issue by adamvduke** [logstash-plugins/logstash-output-s3#3]
It would be valuable to have the ability to configure the plugin to compress files before uploading them to s3. At the moment we manually download, compress, upload, delete uncompressed files. Perhaps something like:

```
s3  {
  ...
  compress => 'gzip'
}
```

This is a feature I'm considering implementing, but I wanted to get a sense of if the maintainers would find this valuable, and/or if there are any other concerns I should be aware of before taking it on.

I see that https://github.com/logstash-plugins/logstash-output-s3/pull/1 is a fairly extensive refactor. Is there a timeline for when that is expected to be merged? I'd like to avoid having to rebase against a large change.

**Comment by oroce** [comment]
Any update on this? Is it decided whether gzip should be a codec or not?
I have a working solution for 1.4: https://github.com/oroce/logstash-output-s3/blob/gzip-configurable-dir/lib/logstash/outputs/s3.rb#L378-L385
But I would love to upgrade to 1.5 and even add gzip support to this module.

**Comment by navatm** [comment]
@oroce I was not able to use your code.
In debug mode I got
S3: file: ls.s3.erans-mini-2.2015-04-16T11.51.tag_s3.part0.txt was put on bucket test-logstash {:level=>:debug, :file=>"logstash/outputs/s3.rb", :line=>"250"}
Without any file in my S3 bucket.
The local temporary file remained empty as well.

**Comment by oroce** [comment]
@navatm hm i was using that module for like 2 months with the following configuration without any problems:
~~~
output {
	stdout { codec => rubydebug }
	s3 {
		bucket => '<bucket>'
		access_key_id => '<access>'
		endpoint_region => 'eu-west-1'
		format => 'json'
		secret_access_key => '<secret>'
		#time_file => 5
		size_file => 504800
		gzip => true
	}
}
~~~

Sadly I'm not using it anymore, because I implemented it just for one of my sideprojects.

**Comment by shribigb** [comment]
@ph When this is going to be merged? I would like to have this compression support.

**Comment by navatm** [comment]
@shribigb we've been working with https://github.com/adience-code/logstash-output-s3 on production for a month. No error yet any problems, ~100GB a day, compress and flush every 4 hours.

**Comment by shaharmor** [comment]
+1

**Comment by navatm** [comment]
Since your name is familiar, I just added a pull request.

**Comment by vpack** [comment]
+1

**Comment by parangdae** [comment]
+1

**Comment by robinup** [comment]
+1

**Comment by koma85** [comment]
+1

**Comment by angad** [comment]
+1

**Comment by fabio-santos-movile** [comment]
+1

**Comment by adamvduke** [comment]
Looks like this should be closed based on https://github.com/logstash-plugins/logstash-output-s3/pull/18 getting merged. Thanks @a86c6f7964 and @suyograo !
