### ISSUE TITLE
Dynamic Prefix: Support configuring uploaded file paths/names within a bucket

### ISSUE THREAD

**Issue by adamvduke** [logstash-plugins/logstash-output-s3#4]
The current version of the plugin stores all of the uploaded files in the root of the configured bucket. It would be valuable to be able to configure the path and filename within the bucket to allow for ease of longtime archiving without having to scroll through 1000's of files when viewing the contents of the bucket. Maybe a static configuration, or a proc that can be eval'd before uploading the new file?

```
s3 {
  ...
  path => "{year}/{month}/{day}/{hour}/{host}{uuid}"
  path_proc => '{|time|  "#{time.year}/#{time.month}/#{time.day}/#{time.hour}/#{Socekt.gethostname}#{uuid}'
}
```

**Comment by pruthvintss** [comment]
Hey, is there an update on how this can be done? would like to configure the path with event fields

**Comment by bradleyphipps** [comment]
This would definitely be useful. Outputting to folders within in a bucket based on their type would make data archival/retention/deletion processes easier to manage/safer. Sadly the following config doesn't work: `bucket => "logstash-output-bucket/%{type}"`

**Comment by radupantiru** [comment]
+1

**Comment by shangliuyan** [comment]
+1

**Comment by wiibaa** [comment]
S3 newbie question,
does this request means that 
1. the @prefix config should be able to use event data like `%{type}/` or `%{+YYYY}/%{+MM}/%{dd}/ ??to specify a "folder structure"
2. the filename itself currently generated in [this method](https://github.com/logstash-plugins/logstash-output-s3/blob/master/lib/logstash/outputs/s3.rb#L306-L315) should be able to use event data ?

If this is right, I could dig in further, most probably looking for 1. first
Thoughts ?

**Comment by adamvduke** [comment]
It looks like there are several implementations of this feature to varying degrees. I'm currently not focused on this issue, but perhaps someone on this thread could contribute to one of the open PR's to one/more/all of them along.

https://github.com/logstash-plugins/logstash-output-s3/pull/44
https://github.com/logstash-plugins/logstash-output-s3/pull/59
https://github.com/logstash-plugins/logstash-output-s3/pull/70
https://github.com/logstash-plugins/logstash-output-s3/pull/81

**Comment by FlorinAndrei** [comment]
The `prefix` parameter for the S3 output plugin now (v5.2.0 or newer) supports string interpolation based on field values.

```
s3 {
  prefix => "logstash-test/%{event}/"
}
```
