### ISSUE TITLE
plugin fail if tags is not defined on config file

### ISSUE THREAD

**Issue by egarbi** [logstash-plugins/logstash-output-s3#5]
According to documentation, default value for tags is "[]", and it is not required.
However, this error is coming if I don’t define tags on config file:
```
NoMethodError: undefined method `join' for nil:NilClass
  format_message at /opt/logstash/lib/logstash/outputs/s3.rb:351
         receive at /opt/logstash/lib/logstash/outputs/s3.rb:302
          handle at /opt/logstash/lib/logstash/outputs/base.rb:86
      initialize at (eval):41
            call at org/jruby/RubyProc.java:271
          output at /opt/logstash/lib/logstash/pipeline.rb:266
    outputworker at /opt/logstash/lib/logstash/pipeline.rb:225
   start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152
```

**Comment by ph** [comment]
Thank you for reporting this bug, It will be fixed once this PR is merged
https://github.com/logstash-plugins/logstash-output-s3/pull/1, this PR add initial support for supporting codecs for the output format. We have extracted the S3 format in the new [s3_plain](https://github.com/logstash-plugins/logstash-codec-s3plain) codec and fix the tag nil issue.

**Comment by ph** [comment]
Fixed in the latest mater, you need to use the https://github.com/logstash-plugins/logstash-codec-s3plain codec.

**Comment by egarbi** [comment]
Ok, thanks, Ill try
