### ISSUE TITLE
Support v4 Signature

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-s3#51]
We need to resolve errors like `"Error: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4"`. We can fix this by adding an option to instantiate the library with `AWS::S3::Client.new(:s3_signature_version => :v4)`.

**Comment by ph** [comment]
Yup that would fix the issue, thanks for taking care of it.

**Comment by andrewvc** [comment]
@ph I don't see that option [anywhere](https://github.com/aws/aws-sdk-ruby/search?utf8=%E2%9C%93&q=s3_signature_version) in the source. Do you know if its legit? Do you know if we depend on the proper version to support it?

**Comment by ph** [comment]
That might be an SDKv2 feature?

**Comment by ph** [comment]
Oh I think that might be a sdk v2 feature.

This should work.
Ruby SDK - Version 1: Set the :s3_signature_version parameter to :v4 when constructing the client.

s3 = AWS::S3::Client.new(:s3_signature_version => :v4)

**Comment by ph** [comment]
@andrewvc the way the aws client work, this is especially true for v2, they build the client api from their api definition. So most features or options wont be found in the source code of the library.

**Comment by ph** [comment]
fixed in #54
