### ISSUE TITLE
"server side" encryption

### ISSUE THREAD

**Issue by mattupstate** [logstash-plugins/logstash-output-s3#62]
It would be nice to have an option to turn on [server side encryption](http://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html) for S3 data

**Comment by fatdrag0n** [comment]
Right now I have all logs systematcially very secure from our nodes to ELK server and we have it also stored on encrypted drive on aws instance. All of our data at this time, need to be transmitted securely in transit end-to-end and also at rest. S3 output plugin does communicate with use_ssl to s3 , which is great. but we need the s3 server side encryption request header to be requested from s3 output plugin.
We have three options from http://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html and we are going with option1 , which I enabled the policy http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html for S3:PutObject to included header s3:x-amz-server-side-encryption":"AES256" and s3 output plugin is failing and is not sending our logs to s3.  Server side will encrypt our data before writing and it will decrypt our data when we download from s3. We really need this feature. Thank you very much for your consideration.

**Comment by MrPrimate** [comment]
Is it possible to get the changes from https://github.com/logstash-plugins/logstash-output-s3/pull/69 merged into the v2 stream for use with older logstash?

**Comment by gkhasel1** [comment]
I would also like to see this merged and compatible with logstash 2

**Comment by sanjay-varanasi** [comment]
Would love to see this for use with Logstash 2.x

**Comment by mattupstate** [comment]
@gkhasel1 #69

**Comment by ph** [comment]
#69 was merged in.

**Comment by jordansissel** [comment]
This is available for Logstash 2.4.x and Logstash 5. I tested Logstash 2.4.1 myself and verified.
