### ISSUE TITLE
Add a custom host for s3 output plugin

### ISSUE THREAD

**Issue by jindov** [logstash-plugins/logstash-output-s3#65]
Dear logstash devs,

I setup a ceph storage system like this http://docs.ceph.com/ and now I want to output log to ceph by s3 api http://docs.ceph.com/docs/v0.80.5/radosgw/s3/ruby/ but default s3 of logstash just support s3 aws, please add a function to custom s3 host to use with ceph storage, example: s3.mystorage.net

The output settings may like this:

output {
s3ceph {
url_endpoint => "s3.mystorage.net"
access_key_id => "my-access-key"
secret_access_key => "my-access-secret-key"
bucket => "logstash-output"
use_ssl => false
}
}

Thank you,

**Comment by jordansissel** [comment]
+1 on supporting a host. Let's see what Boto, s3cmd, and other tools call this setting and see if we can align.

**Comment by jrha** [comment]
:+1:

**Comment by koma85** [comment]
+1 absolutely a must have!

**Comment by koma85** [comment]
There is already someone who as successfully completed the endpoint configuration:
https://github.com/alex-raoul/logstash-output-s3/commit/b11f671fe05e14c68ccec08d7b90b50405ceef8e
and someone who as created the gzip support:
https://github.com/redbubble/logstash-output-s3/commit/fec0505600a06f7d4902d3ec6b30da2ae9281ac6

**Comment by jenshadlich** [comment]
+1 this is definitely a feature we need, please bring it up in the main line

**Comment by atta** [comment]
+1 please merge it

**Comment by rvrignaud** [comment]
Really need it too. +1

**Comment by nich07as** [comment]
+1  - helpful for CEPH implementations.

**Comment by jordansissel** [comment]
Please don't leave +1 comments on this issue. Every +1 comment sends an email to hundreds of people.

I have deleted all the +1 comments  on this issue. At the time of deletion, there were 7 different comments with "+1".

**Comment by jordansissel** [comment]
There's a PR in-progress for this: #100

**Comment by jsvd** [comment]
the mixin used in all s3 plugins [now has endpoint setting available](https://github.com/logstash-plugins/logstash-mixin-aws/pull/32)

As soon as the mixin is released and documentation is added, this feature will be supported in the s3, kinesis and sqs plugins.
