### ISSUE TITLE
S3 file content from logstash-output-s3 plugin

### ISSUE THREAD

**Issue by jgreene-VSLLC** [logstash-plugins/logstash-output-s3#73]
I have ELK on Centos 7 with the Logstash-output-s3 plugin configured, however the content of the files in s3 contain only the following:

```
2016-03-28T11:33:23.000Z 10.x.x.10 %{message}
2016-03-28T11:33:23.000Z 10.x.x.10 %{message}
2016-03-28T11:33:23.000Z 10.x.x.10 %{message}
2016-03-28T11:33:23.000Z 10.x.x.10 %{message}
2016-03-28T11:33:23.000Z 10.x.x.10 %{message}
2016-03-28T11:33:31.000Z 10.x.x.100 %{message}
2016-03-28T11:33:32.000Z 10.x.x.100 %{message}
2016-03-28T11:33:33.000Z 10.x.x.100 %{message}
2016-03-28T11:33:43.000Z 10.x.x.201 %{message}
2016-03-28T11:33:51.000Z 10.x.x.100 %{message}
2016-03-28T11:33:51.000Z 10.x.x.100 %{message}
```

I am new to Logstash and would like to know how to troubleshoot this condition. Logs in logstash are parsed properly and appear in Kibana, normally.

**Comment by ph** [comment]
Could you share your configuration and what logstash version you are using?

**Comment by jgreene-VSLLC** [comment]
Hi, 

I built the logstash server from the following directions: [ELK on CentOS](https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-centos-7l)

########################################################
My versions are as follows:
[root@logserver centos]# java -version = openjdk version "1.8.0_77"
[root@logserver centos]# /opt/logstash/bin/logstash --version = logstash 2.2.2
[root@logserver centos]# curl -XGET 'localhost:9200'
{
  "name" : "Conquistador",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.2.1",
    "build_hash" : "d045fc29d1932bce18b2e65ab8b297fbf6cd41a1",
    "build_timestamp" : "2016-03-09T09:38:54Z",
    "build_snapshot" : false,
    "lucene_version" : "5.4.1"
  },
  "tagline" : "You Know, for Search"
}

Kibana = 4.4
################################################
I have 4 config files:
[root@logserver centos]# ls /etc/logstash/conf.d/
02-beats-input.conf  10-default.conf  10-syslog-filter.conf  30-elasticsearch-output.conf
[root@logserver centos]#

[10-default.conf.txt](https://github.com/logstash-plugins/logstash-output-s3/files/194567/10-default.conf.txt)
[10-syslog-filter.conf.txt](https://github.com/logstash-plugins/logstash-output-s3/files/194566/10-syslog-filter.conf.txt)
[30-elasticsearch-output.conf.txt](https://github.com/logstash-plugins/logstash-output-s3/files/194568/30-elasticsearch-output.conf.txt)
[02-beats-input.conf.txt](https://github.com/logstash-plugins/logstash-output-s3/files/194569/02-beats-input.conf.txt)

Please let me know if you need anything additional.

**Comment by ph** [comment]
I suggest you use the json format for the s3 output, this will save the current logstash event in a structured way so you shouldn't miss any fields from either windows or linux.

```
output {
   s3{
     access_key_id => "A-Z"
     secret_access_key => "1-10"
     region => "us-gov-west-1"
     bucket => "logs"
     size_file => 2048
     time_file => 3
     codec => json_lines
     canned_acl => "private"
     temporary_directory => "/opt/logstash/S3_temp/"
     use_ssl => "true"
   }
}
```

**Comment by jgreene-VSLLC** [comment]
Thank you. I have reviewed multiple files and see no remnant of the condition reported. Thank you for developing this plugin, it is most helpful.

**Comment by zhongyu211** [comment]
anyone know how to just move the message field to s3 but not @timestame and host fields.

**Comment by anvaughan-w3w** [comment]
@zhongyu211 , you may have fixed this since asking here, but I had the exact same issue and found it was down to my filter removing the %{message} after groking it. My guess is the S3 output plugin writes "%{message}" as a string if it is not defined.

Hope this helped.

**Comment by anvaughan** [comment]
@zhongyu211 , you may have fixed this since asking here, but I had the exact same issue and found it was down to my filter removing the %{message} after groking it. My guess is the S3 output plugin writes "%{message}" as a string if it is not defined. Hope this helped.

**Comment by VinitaT** [comment]
@zhongyu211 ,@anvaughan ..I am facing the same issue...can you please share your solution.

**Comment by VinitaT** [comment]
I got the solution. just add below line in s3 outpt section

codec => line { format => "%{message}" }
