### ISSUE TITLE
S3 output Plugin does not supports canned_acl => "bucket_owner_full_control"

### ISSUE THREAD

**Issue by devanshusrivastava** [logstash-plugins/logstash-output-s3#76]
We need the Outputted file from Logstash to S3 to be fully controlled by bucket owner .

Currently only Below Options are available : 

canned_acl => "private"                  (optional. Options are "private", "public_read", "public_read_write", "authenticated_read". Defaults to "private" )

We should add support for  "bucket_owner_full_control"

**Comment by devanshusrivastava** [comment]
@jordansissel Please review

**Comment by mummylegs** [comment]
Here is the full list of canned ACLs:

http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

private, public-read, public-read-write, aws-exec-read, authenticated-read, bucket-owner-read, bucket-owner-full-control, log-delivery-write

Also not sure if it makes a difference but the official aws documentation (link above) uses hyphens -- the documentation quoted above uses underscores.  Not sure which one the conf files actually accept.

**Comment by mummylegs** [comment]
Just tested and got the following in the logs:

Invalid setting for s3 output plugin:

```
  output {
    s3 {
      # This setting must be a ["private", "public_read", "public_read_write", "authenticated_read"]
      # Expected one of ["private", "public_read", "public_read_write", "authenticated_read"], got ["authenticated-read"]
      canned_acl => "authenticated-read"
      ...
    }
  }
```
So, it would seem that the plugin rejects hyphens.

**Comment by MrPrimate** [comment]
How do I get my fix for this issue reviewed and merged? it's been hanging around for a third of a year now.
