### ISSUE TITLE
Use STS/IAM to assume a role

### ISSUE THREAD

**Issue by MrPrimate** [logstash-plugins/logstash-output-s3#84]
Is it possible to assume a role to get credentials to deliver to an S3 bucket?

Use case - I want to be able to deliver the output to an S3 bucket in a different AWS account, without having to provide credentials in a config file.

**Comment by lmello** [comment]
You don't need sts. 

Account 1: Create an iam role assign to the instance that will upload the logs. Give permission in this role to the bucket you want to put the files .

Account 2: edit the bucket policy to allow access from account 1.

In the config file don't put auth information the plugin will use the instance profile .

**Comment by ph** [comment]
Instance profile is the way to go in that case.
