### ISSUE TITLE
Update Docs for S3 Output Plugin

### ISSUE THREAD

**Issue by rcuza** [logstash-plugins/logstash-output-s3#88]
As a user, I would expect Event Dependent Configurations to work with the Logstash Output S3 plugin's "prefix" config. This is not the case. I discovered this in a [community discussion](https://discuss.elastic.co/t/dynamic-bucket-names-or-directories-in-aws-s3-output/2459/2) instead of in the [documentation](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-s3.html).

Please update the documentation to state that Event Dependent Configurations do not work with the "prefix" config.

Thank you.
- Version: 2.3.3
- Operating System: ALL
- Config File (if you have sensitive info, please remove it): N/A
- Sample Data: N/A
- Steps to Reproduce: See community discussion

**Comment by ph** [comment]
Event dependent prefix now work with 4.0.0 version and up of this plugin.
