### ISSUE TITLE
Ability to Use sprintf Dynamic Config in Logstash-Output-S3 Plugin

### ISSUE THREAD

**Issue by rcuza** [logstash-plugins/logstash-output-s3#89]
As a user I would like to be able to use `sprintf` dynamic configurations in the `prefix` configuration of the logstash-output-s3 plugin. 

As stated by Magnus Bäck in a [community discussion](https://discuss.elastic.co/t/dynamic-bucket-names-or-directories-in-aws-s3-output/2459/2), this would be complicated to implement in a general way because of the complexities of storing the files before uploading them to S3. However a config like `prefix => events/%{+yyyy.MM.dd}` would only change once a day.

**Comment by ph** [comment]
I am closing this issue in favor of #4, so all the discussion can happen in the same place.
I have started on working on that feature.
